### ISSUE TITLE
Mod 182

### ISSUE THREAD

**Issue by asunyer90** [podemos-info/participa#13]
Hello!! 
There's anything made for generation of file to send to "Hacienda" with all donations? For mod. 182 :)
Aswell.. something to send kind a certificate/letter with all donations made by a member?

Regards

**Comment by leio10** [comment]
Hi, I'm sorry but the answer for both questions is no. :disappointed:

Also, we are working in a new platform to replace this, so there won't be any advance of that kind in the future.
